services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    public: false
    bind:
      Psr\Log\LoggerInterface: '@profilepage.logger'

  # Services
  SimpleSAML\Module\profilepage\:
    resource: '../../src/*'
    exclude: '../../src/{Http/Controllers}'
  # Service aliases
  profilepage.logger:
    class: SimpleSAML\Module\profilepage\Services\Logger
  # Controllers
  SimpleSAML\Module\profilepage\Http\Controllers\:
    resource: '../../src/Http/Controllers/*'
    tags: ['controller.service_arguments']