services:
  # default configuration for services in *this* file
  _defaults:
    public: false

  SimpleSAML\Module\accounting\ModuleConfiguration:
    class: SimpleSAML\Module\accounting\ModuleConfiguration