
accounting-admin-configuration-status:
    path:       /admin/configuration/status
    controller: SimpleSAML\Module\accounting\Http\Controllers\Admin\Configuration::status

accounting-user-personal-data:
    path: /user/personal-data
    controller: SimpleSAML\Module\accounting\Http\Controllers\User\Profile::personalData

accounting-user-connected-organizations:
    path: /user/connected-organizations
    controller: SimpleSAML\Module\accounting\Http\Controllers\User\Profile::connectedOrganizations

accounting-user-activity:
    path: /user/activity
    controller: SimpleSAML\Module\accounting\Http\Controllers\User\Profile::activity

accounting-user-oidc-token-revoke-xhr:
    path: /user/oidc-tokens/revoke-xhr
    controller: SimpleSAML\Module\accounting\Http\Controllers\User\Profile::oidcTokenRevokeXhr
    methods: POST

accounting-user-logout:
    path: /user/logout
    controller: SimpleSAML\Module\accounting\Http\Controllers\Logout::logout
    methods:
        - GET
        - POST

accounting-logout:
    path: /logged-out
    controller: SimpleSAML\Module\accounting\Http\Controllers\Logout::loggedOut