
profilepage-admin-configuration-status:
    path:       /admin/configuration/status
    controller: SimpleSAML\Module\profilepage\Http\Controllers\Admin\Configuration::status

profilepage-user-personal-data:
    path: /user/personal-data
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::personalData

profilepage-user-personal-data-csv:
    path: /user/personal-data/csv
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::personalDataCsv

profilepage-user-connected-organizations:
    path: /user/connected-organizations
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::connectedOrganizations

profilepage-user-connected-organizations-csv:
    path: /user/connected-organizations/csv
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::connectedOrganizationsCsv

profilepage-user-activity:
    path: /user/activity
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::activity

profilepage-user-activity-csv:
    path: /user/activity/csv
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::activityCsv

profilepage-user-oidc-token-revoke-xhr:
    path: /user/oidc-tokens/revoke-xhr
    controller: SimpleSAML\Module\profilepage\Http\Controllers\User\Profile::oidcTokenRevokeXhr
    methods: POST

profilepage-user-logout:
    path: /user/logout
    controller: SimpleSAML\Module\profilepage\Http\Controllers\Logout::logout
    methods:
        - GET
        - POST

profilepage-logout:
    path: /logged-out
    controller: SimpleSAML\Module\profilepage\Http\Controllers\Logout::loggedOut