
# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
#cache:
#  # We key the cache using the commit unique identifier.
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - vendor/

# List of stages for jobs, and their order of execution
stages:
  - test
  - deploy

# PHP v7.4
test-74:
  tags:
    - niif-hu-docker
  stage: test
  image: cicnavi/dap:74
  script:
    - composer install --prefer-dist --no-progress --no-suggest
    - vendor/bin/psalm --clear-cache
    - composer run-script pre-commit

# PHP v8.1
test-81:
  tags:
    - niif-hu-docker
  stage: test
  image: cicnavi/dap:81
  script:
    - composer install --prefer-dist --no-progress --no-suggest
    - vendor/bin/psalm --clear-cache
    - composer run-script pre-commit

# TODO mivanci remove when GEANT project finishes
# Do some updates on the test deployment...
niif-update:
  tags:
    - niif-hu-shell
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  #      when: manual
  script:
    - cd /var/www/simplesamlphp
    - composer update -n cicnavi/simplesamlphp-module-accounting
